Q1. Consider the following sensor readings:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
A sensor has an average measurement error of +2°C.
Perform the following without using a for loop:


a. Add 2°C to every reading using vectorization.


b. Convert all temperatures from Celsius to Fahrenheit using:
F = 9 /
5 C + 32


c. Identify all readings greater than 32°C using Boolean indexing.


d. Count how many readings exceed 32°C.


e. Explain how vectorization and Boolean indexing can make data processing more efficient
than explicitly iterating through every value.

In [ ]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 28, 27, 33, 40])

a = temperature + 2
print(a)

b = (9/5) * a + 32
print(b)

c = a[a > 32]
print(c)

d = np.sum(a > 32)
print(d)

# Vectorization and Boolean indexing make data processing faster and easier because they work on the whole NumPy array at once without using explicit for loops.


[27 30 33 37 30 29 35 42]
[ 80.6  86.   91.4  98.6  86.   84.2  95.  107.6]
[33 37 35 42]
4


Q2. The following matrix represents the number of daily steps recorded by four users
over three days:
steps = np.array([
[5000, 6200, 7100],
[8000, 7500, 9000],
[4500, 5100, 4800],
[9000, 8500, 9500]])
Perform the following:


a. Calculate the total steps recorded.


b. Calculate the mean number of steps.


c. Find the maximum and minimum values.


d. Calculate the total steps for each day using axis=0.


e. Calculate the total steps for each user using axis=1.


f. Find the user/day position containing the maximum number of steps using argmax().

In [ ]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print(np.sum(steps))
print(np.mean(steps))
print(np.max(steps))
print(np.min(steps))
print(np.sum(steps, axis=0))
print(np.sum(steps, axis=1))

position = np.unravel_index(np.argmax(steps), steps.shape)
print(position)


84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
(np.int64(3), np.int64(2))


Q3. Write a Python program using NumPy to perform the following operations:


a. Create the following NumPy array:
original = np.array([1, 2, 3, 4, 5, 6])


b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset.


c. Modify the first element of subset to 999 and display both original and subset.


d. Create another slice from original, but this time use .copy(). Modify its first element to 500
and display original and the copied array.


e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it
into a 3 × 4 matrix.


f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:
• First row
• Last row
• Second column
• Elements from rows 1–2 and columns 2–3


g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel().


h. Modify an element in the array returned by ravel() and observe whether the original array is
affected.


i. Modify an element in the array returned by flatten() and observe whether the original array is
affected.


j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.

In [ ]:
import numpy as np

# a
original = np.array([1, 2, 3, 4, 5, 6])
print(original)

# b
subset = original[1:5]
print(subset)

# c
subset[0] = 999
print(original)
print(subset)

# d
copied = original[1:5].copy()
copied[0] = 500
print(original)
print(copied)

# e
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

# f
print(matrix[0])
print(matrix[-1])
print(matrix[:, 1])
print(matrix[1:3, 2:4])

# g
flat1 = matrix.flatten()
flat2 = matrix.ravel()
print(flat1)
print(flat2)

# h
flat2[0] = 100
print(matrix)

# i
flat1[0] = 200
print(matrix)

# j
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)


[1 2 3 4 5 6]
[2 3 4 5]
[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[ 7  8]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
(3, 4)
2
12
int64


Q4. A simple cognitive-assistive system wants to predict a user's assistance score based
on three factors:
• Sleep hours
• Activity level
• Stress level
Consider:
X = np.array([
[6, 70, 3],
[5, 50, 6],
[8, 80, 2],
[4, 30, 8]
])
y = np.array([40, 65, 30, 85])
Here, each row represents one user and each column represents a feature.
Perform the following:


a. Display the shape and dimensions of X.


b. Calculate: X.T and explain what the transpose represents.


c. Calculate the matrix product: X.T @ X


d. Calculate the matrix inverse using: np.linalg.inv() where appropriate.


e. Implement the Ordinary Least Squares equation: 𝛽 = (𝑋!𝑋)"#𝑋!𝑦 using NumPy.


f. Explain what the resulting coefficients represent in the context of the three user
features.


g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to
obtain a predicted assistance score.

In [ ]:
import numpy as np

# Given data
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# a
print("Shape:", X.shape)
print("Dimensions:", X.ndim)

# b
print("Transpose:")
print(X.T)

# c
print("X.T @ X:")
print(X.T @ X)

# d
inverse = np.linalg.inv(X.T @ X)
print("Inverse:")
print(inverse)

# e
beta = inverse @ X.T @ y
print("Coefficients:")
print(beta)

# f
print("Prediction equation:")
print("y =", beta[0], "* Sleep +", beta[1], "* Activity +", beta[2], "* Stress")

# g
new_user = np.array([5, 40, 7])
prediction = new_user @ beta
print("Predicted score:", prediction)


Shape: (4, 3)
Dimensions: 2
Transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients:
[-0.15921454  0.14083853 10.06302242]
Prediction equation:
y = -0.1592145415946895 * Sleep + 0.14083852991906243 * Activity + 10.063022422714587 * Stress
Predicted score: 75.27862544779117
