Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Original Array:", arr)

addition = arr + 2
print("After adding 2:", addition)

multiplication = arr * 3
print("After multiplying by 3:", multiplication)

division = arr / 2
print("After dividing by 2:", division)


Original Array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original Array:", arr)

reverse = arr[::-1]
print("Reversed Array:", reverse)

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

print("Most frequent element in x:", np.bincount(x).argmax())
print("Indices of most frequent element in x:", np.where(x == np.bincount(x).argmax())[0])

print("Most frequent element in y:", np.bincount(y).argmax())
print("Indices of most frequent element in y:", np.where(y == np.bincount(y).argmax())[0])


Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]
Most frequent element in x: 1
Indices of most frequent element in x: [0 5 7 8 9]
Most frequent element in y: 1
Indices of most frequent element in y: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])


1st row, 2nd column: 20
3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np

Mokksh = np.linspace(10, 100, 25)

print("Array:")
print(Mokksh)

print("Dimensions:", Mokksh.ndim)
print("Total elements:", Mokksh.size)
print("Data type of each element:", Mokksh.dtype)
print("Total bytes consumed:", Mokksh.nbytes)

transpose_reshape = Mokksh.reshape(25, 1)

print("Transpose using reshape():")
print(transpose_reshape)

transpose_T = Mokksh.T

print("Using T attribute:")
print(transpose_T)



Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Total elements: 25
Data type of each element: float64
Total bytes consumed: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
import numpy as np

ucs420_Mokksh = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Mokksh)

print("Mean:", np.mean(ucs420_Mokksh))
print("Median:", np.median(ucs420_Mokksh))
print("Maximum:", np.max(ucs420_Mokksh))
print("Minimum:", np.min(ucs420_Mokksh))
print("Unique Elements:", np.unique(ucs420_Mokksh))

reshaped_ucs420_Mokksh = ucs420_Mokksh.reshape(4, 3)
print("Reshaped Array:")
print(reshaped_ucs420_Mokksh)

resized_ucs420_Mokksh = np.resize(ucs420_Mokksh, (2, 3))
print("Resized Array:")
print(resized_ucs420_Mokksh)


Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
[[10 20 30]
 [40 50 60]]
